//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMessager
    {
        public int Id { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> GroupMemberId { get; set; }
        public Nullable<int> MessageType { get; set; }
        public string Content { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CrateTime { get; set; }
        public Nullable<int> CrateUseId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual GroupMember GroupMember { get; set; }
        public virtual Group Group { get; set; }
    }
}
