//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Authorizations = new HashSet<Authorization>();
            this.Authorizations1 = new HashSet<Authorization>();
            this.DocReaders = new HashSet<DocReader>();
            this.DocSenders = new HashSet<DocSender>();
            this.JobChanges = new HashSet<JobChange>();
        }
    
        public int ID { get; set; }
        public string PostName { get; set; }
        public string MarkerString { get; set; }
        public string Descript { get; set; }
        public Nullable<int> PostID { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string IsDeleted { get; set; }
        public string Notes { get; set; }
        public string State { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int UpdateUserId { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Authorization> Authorizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Authorization> Authorizations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocReader> DocReaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocSender> DocSenders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobChange> JobChanges { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
